//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FermeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public decimal ID_CLIENTE { get; set; }
        public string RUT_CLI { get; set; }
        public string NOMBRES { get; set; }
        public string APELLIDOS { get; set; }
        public Nullable<System.DateTime> NACIMIENTO { get; set; }
        public Nullable<decimal> FONO { get; set; }
        public string EMAIL { get; set; }
        public decimal ID_TIPO { get; set; }
        public decimal ID_USUARIO { get; set; }
    
        public virtual TIPO_CLIENTE TIPO_CLIENTE { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
