//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FermeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA
    {
        public FACTURA()
        {
            this.DETALLE_FACTURA = new HashSet<DETALLE_FACTURA>();
        }
    
        public decimal ID_FACTURA { get; set; }
        public System.DateTime FECHA_INGRESO { get; set; }
        public decimal IVA { get; set; }
        public decimal SUB_TOTAL { get; set; }
        public decimal TOTAL { get; set; }
        public Nullable<decimal> ID_USUARIO { get; set; }
        public Nullable<decimal> ID_ESTADO { get; set; }
        public decimal ID_PAGO { get; set; }
        public string DESPACHO { get; set; }
    
        public virtual ICollection<DETALLE_FACTURA> DETALLE_FACTURA { get; set; }
        public virtual ESTADO_COMPRA ESTADO_COMPRA { get; set; }
        public virtual METODO_PAGO METODO_PAGO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
