//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FermeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAMILIA_PROD
    {
        public FAMILIA_PROD()
        {
            this.PRODUCTO = new HashSet<PRODUCTO>();
            this.TIPO_PROD = new HashSet<TIPO_PROD>();
        }
    
        public decimal ID_FAMILIA { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<PRODUCTO> PRODUCTO { get; set; }
        public virtual ICollection<TIPO_PROD> TIPO_PROD { get; set; }
    }
}
