//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FermeDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class FermeEntities : DbContext
    {
        public FermeEntities()
            : base("name=FermeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BOLETA> BOLETA { get; set; }
        public DbSet<CARGO> CARGO { get; set; }
        public DbSet<CARRITO> CARRITO { get; set; }
        public DbSet<CLIENTE> CLIENTE { get; set; }
        public DbSet<DETALLE_BOLETA> DETALLE_BOLETA { get; set; }
        public DbSet<DETALLE_FACTURA> DETALLE_FACTURA { get; set; }
        public DbSet<DETALLE_ORDEN> DETALLE_ORDEN { get; set; }
        public DbSet<DOMICILIO> DOMICILIO { get; set; }
        public DbSet<EMPLEADO> EMPLEADO { get; set; }
        public DbSet<ESTADO_COMPRA> ESTADO_COMPRA { get; set; }
        public DbSet<ESTADO_ORDEN> ESTADO_ORDEN { get; set; }
        public DbSet<FACTURA> FACTURA { get; set; }
        public DbSet<FAMILIA_PROD> FAMILIA_PROD { get; set; }
        public DbSet<FOTO_PROD> FOTO_PROD { get; set; }
        public DbSet<METODO_PAGO> METODO_PAGO { get; set; }
        public DbSet<ORDEN_COMPRA> ORDEN_COMPRA { get; set; }
        public DbSet<PRODUCTO> PRODUCTO { get; set; }
        public DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public DbSet<RUBRO> RUBRO { get; set; }
        public DbSet<TIPO_CLIENTE> TIPO_CLIENTE { get; set; }
        public DbSet<TIPO_PROD> TIPO_PROD { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
    
        public virtual int SP_ADD_CARRITO(Nullable<decimal> v_ID_USUARIO, Nullable<decimal> v_ID_PRODUCTO, ObjectParameter v_SALIDA)
        {
            var v_ID_USUARIOParameter = v_ID_USUARIO.HasValue ?
                new ObjectParameter("V_ID_USUARIO", v_ID_USUARIO) :
                new ObjectParameter("V_ID_USUARIO", typeof(decimal));
    
            var v_ID_PRODUCTOParameter = v_ID_PRODUCTO.HasValue ?
                new ObjectParameter("V_ID_PRODUCTO", v_ID_PRODUCTO) :
                new ObjectParameter("V_ID_PRODUCTO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ADD_CARRITO", v_ID_USUARIOParameter, v_ID_PRODUCTOParameter, v_SALIDA);
        }
    
        public virtual int SP_CREATE_CLIENTE(string v_USERNAME, string v_RUT, string v_NOMBRES, string v_APELLIDOS, string v_NACIMIENTO, Nullable<decimal> v_FONO, string v_EMAIL, Nullable<decimal> v_ID_TIPO, ObjectParameter v_SALIDA)
        {
            var v_USERNAMEParameter = v_USERNAME != null ?
                new ObjectParameter("V_USERNAME", v_USERNAME) :
                new ObjectParameter("V_USERNAME", typeof(string));
    
            var v_RUTParameter = v_RUT != null ?
                new ObjectParameter("V_RUT", v_RUT) :
                new ObjectParameter("V_RUT", typeof(string));
    
            var v_NOMBRESParameter = v_NOMBRES != null ?
                new ObjectParameter("V_NOMBRES", v_NOMBRES) :
                new ObjectParameter("V_NOMBRES", typeof(string));
    
            var v_APELLIDOSParameter = v_APELLIDOS != null ?
                new ObjectParameter("V_APELLIDOS", v_APELLIDOS) :
                new ObjectParameter("V_APELLIDOS", typeof(string));
    
            var v_NACIMIENTOParameter = v_NACIMIENTO != null ?
                new ObjectParameter("V_NACIMIENTO", v_NACIMIENTO) :
                new ObjectParameter("V_NACIMIENTO", typeof(string));
    
            var v_FONOParameter = v_FONO.HasValue ?
                new ObjectParameter("V_FONO", v_FONO) :
                new ObjectParameter("V_FONO", typeof(decimal));
    
            var v_EMAILParameter = v_EMAIL != null ?
                new ObjectParameter("V_EMAIL", v_EMAIL) :
                new ObjectParameter("V_EMAIL", typeof(string));
    
            var v_ID_TIPOParameter = v_ID_TIPO.HasValue ?
                new ObjectParameter("V_ID_TIPO", v_ID_TIPO) :
                new ObjectParameter("V_ID_TIPO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_CLIENTE", v_USERNAMEParameter, v_RUTParameter, v_NOMBRESParameter, v_APELLIDOSParameter, v_NACIMIENTOParameter, v_FONOParameter, v_EMAILParameter, v_ID_TIPOParameter, v_SALIDA);
        }
    
        public virtual int SP_CREATE_EMPLEADO(string v_USERNAME, string v_PASSWORD, string v_RUT, string v_NOMBRE, string v_APELLIDOS, Nullable<decimal> v_ID_CARGO, ObjectParameter v_SALIDA)
        {
            var v_USERNAMEParameter = v_USERNAME != null ?
                new ObjectParameter("V_USERNAME", v_USERNAME) :
                new ObjectParameter("V_USERNAME", typeof(string));
    
            var v_PASSWORDParameter = v_PASSWORD != null ?
                new ObjectParameter("V_PASSWORD", v_PASSWORD) :
                new ObjectParameter("V_PASSWORD", typeof(string));
    
            var v_RUTParameter = v_RUT != null ?
                new ObjectParameter("V_RUT", v_RUT) :
                new ObjectParameter("V_RUT", typeof(string));
    
            var v_NOMBREParameter = v_NOMBRE != null ?
                new ObjectParameter("V_NOMBRE", v_NOMBRE) :
                new ObjectParameter("V_NOMBRE", typeof(string));
    
            var v_APELLIDOSParameter = v_APELLIDOS != null ?
                new ObjectParameter("V_APELLIDOS", v_APELLIDOS) :
                new ObjectParameter("V_APELLIDOS", typeof(string));
    
            var v_ID_CARGOParameter = v_ID_CARGO.HasValue ?
                new ObjectParameter("V_ID_CARGO", v_ID_CARGO) :
                new ObjectParameter("V_ID_CARGO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_EMPLEADO", v_USERNAMEParameter, v_PASSWORDParameter, v_RUTParameter, v_NOMBREParameter, v_APELLIDOSParameter, v_ID_CARGOParameter, v_SALIDA);
        }
    
        public virtual int SP_CREATE_FOTO_PRODUCTO(Nullable<decimal> v_ID_PRODUCTO, string v_FOTO, ObjectParameter v_SALIDA)
        {
            var v_ID_PRODUCTOParameter = v_ID_PRODUCTO.HasValue ?
                new ObjectParameter("V_ID_PRODUCTO", v_ID_PRODUCTO) :
                new ObjectParameter("V_ID_PRODUCTO", typeof(decimal));
    
            var v_FOTOParameter = v_FOTO != null ?
                new ObjectParameter("V_FOTO", v_FOTO) :
                new ObjectParameter("V_FOTO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_FOTO_PRODUCTO", v_ID_PRODUCTOParameter, v_FOTOParameter, v_SALIDA);
        }
    
        public virtual int SP_CREATE_PRODUCTO(Nullable<decimal> v_ID_PRODUCTO, string v_DESCRIPCION, string v_VENCIMIENTO, Nullable<decimal> v_PRECIO, Nullable<decimal> v_STOCK, Nullable<decimal> v_STOCK_CRITICO, Nullable<decimal> v_ID_PROVEEDOR, Nullable<decimal> v_ID_FAMILIA, ObjectParameter v_SALIDA)
        {
            var v_ID_PRODUCTOParameter = v_ID_PRODUCTO.HasValue ?
                new ObjectParameter("V_ID_PRODUCTO", v_ID_PRODUCTO) :
                new ObjectParameter("V_ID_PRODUCTO", typeof(decimal));
    
            var v_DESCRIPCIONParameter = v_DESCRIPCION != null ?
                new ObjectParameter("V_DESCRIPCION", v_DESCRIPCION) :
                new ObjectParameter("V_DESCRIPCION", typeof(string));
    
            var v_VENCIMIENTOParameter = v_VENCIMIENTO != null ?
                new ObjectParameter("V_VENCIMIENTO", v_VENCIMIENTO) :
                new ObjectParameter("V_VENCIMIENTO", typeof(string));
    
            var v_PRECIOParameter = v_PRECIO.HasValue ?
                new ObjectParameter("V_PRECIO", v_PRECIO) :
                new ObjectParameter("V_PRECIO", typeof(decimal));
    
            var v_STOCKParameter = v_STOCK.HasValue ?
                new ObjectParameter("V_STOCK", v_STOCK) :
                new ObjectParameter("V_STOCK", typeof(decimal));
    
            var v_STOCK_CRITICOParameter = v_STOCK_CRITICO.HasValue ?
                new ObjectParameter("V_STOCK_CRITICO", v_STOCK_CRITICO) :
                new ObjectParameter("V_STOCK_CRITICO", typeof(decimal));
    
            var v_ID_PROVEEDORParameter = v_ID_PROVEEDOR.HasValue ?
                new ObjectParameter("V_ID_PROVEEDOR", v_ID_PROVEEDOR) :
                new ObjectParameter("V_ID_PROVEEDOR", typeof(decimal));
    
            var v_ID_FAMILIAParameter = v_ID_FAMILIA.HasValue ?
                new ObjectParameter("V_ID_FAMILIA", v_ID_FAMILIA) :
                new ObjectParameter("V_ID_FAMILIA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_PRODUCTO", v_ID_PRODUCTOParameter, v_DESCRIPCIONParameter, v_VENCIMIENTOParameter, v_PRECIOParameter, v_STOCKParameter, v_STOCK_CRITICOParameter, v_ID_PROVEEDORParameter, v_ID_FAMILIAParameter, v_SALIDA);
        }
    
        public virtual int SP_CREATE_PROVEEDOR(string v_USERNAME, string v_RUT, string v_NOMBRE, Nullable<decimal> v_FONO, Nullable<decimal> v_ID_RUBRO, ObjectParameter v_SALIDA)
        {
            var v_USERNAMEParameter = v_USERNAME != null ?
                new ObjectParameter("V_USERNAME", v_USERNAME) :
                new ObjectParameter("V_USERNAME", typeof(string));
    
            var v_RUTParameter = v_RUT != null ?
                new ObjectParameter("V_RUT", v_RUT) :
                new ObjectParameter("V_RUT", typeof(string));
    
            var v_NOMBREParameter = v_NOMBRE != null ?
                new ObjectParameter("V_NOMBRE", v_NOMBRE) :
                new ObjectParameter("V_NOMBRE", typeof(string));
    
            var v_FONOParameter = v_FONO.HasValue ?
                new ObjectParameter("V_FONO", v_FONO) :
                new ObjectParameter("V_FONO", typeof(decimal));
    
            var v_ID_RUBROParameter = v_ID_RUBRO.HasValue ?
                new ObjectParameter("V_ID_RUBRO", v_ID_RUBRO) :
                new ObjectParameter("V_ID_RUBRO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_PROVEEDOR", v_USERNAMEParameter, v_RUTParameter, v_NOMBREParameter, v_FONOParameter, v_ID_RUBROParameter, v_SALIDA);
        }
    
        public virtual int SP_LISTAR_CARRITO(Nullable<decimal> v_ID_USUARIO)
        {
            var v_ID_USUARIOParameter = v_ID_USUARIO.HasValue ?
                new ObjectParameter("V_ID_USUARIO", v_ID_USUARIO) :
                new ObjectParameter("V_ID_USUARIO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_LISTAR_CARRITO", v_ID_USUARIOParameter);
        }
    
        public virtual int SP_LISTAR_PRODUCTOS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_LISTAR_PRODUCTOS");
        }
    
        public virtual int SP_LISTAR_TIPOPRODUCTO_POR_FAMILIA(Nullable<decimal> v_ID_FAMILIA)
        {
            var v_ID_FAMILIAParameter = v_ID_FAMILIA.HasValue ?
                new ObjectParameter("V_ID_FAMILIA", v_ID_FAMILIA) :
                new ObjectParameter("V_ID_FAMILIA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_LISTAR_TIPOPRODUCTO_POR_FAMILIA", v_ID_FAMILIAParameter);
        }
    
        public virtual int SP_OBTENER_CANTIDAD_SUBTOTAL_Y_TOTAL(Nullable<decimal> v_ID_USUARIO)
        {
            var v_ID_USUARIOParameter = v_ID_USUARIO.HasValue ?
                new ObjectParameter("V_ID_USUARIO", v_ID_USUARIO) :
                new ObjectParameter("V_ID_USUARIO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_OBTENER_CANTIDAD_SUBTOTAL_Y_TOTAL", v_ID_USUARIOParameter);
        }
    
        public virtual int SP_OBTENER_ID_FOTO_PROD(ObjectParameter v_ID_FOTO_PROD)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_OBTENER_ID_FOTO_PROD", v_ID_FOTO_PROD);
        }
    
        public virtual int SP_OBTENER_ID_PRODUCTO(string v_ID_PROVEEDOR, string v_ID_FAMILIA, string v_VENCIMIENTO, ObjectParameter v_SALIDA)
        {
            var v_ID_PROVEEDORParameter = v_ID_PROVEEDOR != null ?
                new ObjectParameter("V_ID_PROVEEDOR", v_ID_PROVEEDOR) :
                new ObjectParameter("V_ID_PROVEEDOR", typeof(string));
    
            var v_ID_FAMILIAParameter = v_ID_FAMILIA != null ?
                new ObjectParameter("V_ID_FAMILIA", v_ID_FAMILIA) :
                new ObjectParameter("V_ID_FAMILIA", typeof(string));
    
            var v_VENCIMIENTOParameter = v_VENCIMIENTO != null ?
                new ObjectParameter("V_VENCIMIENTO", v_VENCIMIENTO) :
                new ObjectParameter("V_VENCIMIENTO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_OBTENER_ID_PRODUCTO", v_ID_PROVEEDORParameter, v_ID_FAMILIAParameter, v_VENCIMIENTOParameter, v_SALIDA);
        }
    
        public virtual int SP_REGISTRAR_COMPRA(Nullable<decimal> v_ID_USUARIO, Nullable<decimal> v_ID_PAGO, string v_DESPACHO, ObjectParameter v_SALIDA)
        {
            var v_ID_USUARIOParameter = v_ID_USUARIO.HasValue ?
                new ObjectParameter("V_ID_USUARIO", v_ID_USUARIO) :
                new ObjectParameter("V_ID_USUARIO", typeof(decimal));
    
            var v_ID_PAGOParameter = v_ID_PAGO.HasValue ?
                new ObjectParameter("V_ID_PAGO", v_ID_PAGO) :
                new ObjectParameter("V_ID_PAGO", typeof(decimal));
    
            var v_DESPACHOParameter = v_DESPACHO != null ?
                new ObjectParameter("V_DESPACHO", v_DESPACHO) :
                new ObjectParameter("V_DESPACHO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_REGISTRAR_COMPRA", v_ID_USUARIOParameter, v_ID_PAGOParameter, v_DESPACHOParameter, v_SALIDA);
        }
    
        public virtual int SP_UPDATE_CARRITO(Nullable<decimal> v_ID_CARRITO, Nullable<decimal> v_CANTIDAD, ObjectParameter v_SALIDA)
        {
            var v_ID_CARRITOParameter = v_ID_CARRITO.HasValue ?
                new ObjectParameter("V_ID_CARRITO", v_ID_CARRITO) :
                new ObjectParameter("V_ID_CARRITO", typeof(decimal));
    
            var v_CANTIDADParameter = v_CANTIDAD.HasValue ?
                new ObjectParameter("V_CANTIDAD", v_CANTIDAD) :
                new ObjectParameter("V_CANTIDAD", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_CARRITO", v_ID_CARRITOParameter, v_CANTIDADParameter, v_SALIDA);
        }
    
        public virtual int SP_VALIDAR_VENDEDOR(string v_USERNAME, string v_PASSWORD, ObjectParameter v_SALIDA)
        {
            var v_USERNAMEParameter = v_USERNAME != null ?
                new ObjectParameter("V_USERNAME", v_USERNAME) :
                new ObjectParameter("V_USERNAME", typeof(string));
    
            var v_PASSWORDParameter = v_PASSWORD != null ?
                new ObjectParameter("V_PASSWORD", v_PASSWORD) :
                new ObjectParameter("V_PASSWORD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_VALIDAR_VENDEDOR", v_USERNAMEParameter, v_PASSWORDParameter, v_SALIDA);
        }
    
        public virtual int SP_ADD_CARRITO_ESCRITORIO(string v_USERNAME, Nullable<decimal> v_ID_PRODUCTO, ObjectParameter v_SALIDA)
        {
            var v_USERNAMEParameter = v_USERNAME != null ?
                new ObjectParameter("V_USERNAME", v_USERNAME) :
                new ObjectParameter("V_USERNAME", typeof(string));
    
            var v_ID_PRODUCTOParameter = v_ID_PRODUCTO.HasValue ?
                new ObjectParameter("V_ID_PRODUCTO", v_ID_PRODUCTO) :
                new ObjectParameter("V_ID_PRODUCTO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ADD_CARRITO_ESCRITORIO", v_USERNAMEParameter, v_ID_PRODUCTOParameter, v_SALIDA);
        }
    
        public virtual int SP_LISTAR_CARRITO_ESCRITORIO(string v_USERNAME)
        {
            var v_USERNAMEParameter = v_USERNAME != null ?
                new ObjectParameter("V_USERNAME", v_USERNAME) :
                new ObjectParameter("V_USERNAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_LISTAR_CARRITO_ESCRITORIO", v_USERNAMEParameter);
        }
    
        public virtual int SP_OBTENER_ID_USUARIO(string v_USERNAME, ObjectParameter v_ID_USUARIO)
        {
            var v_USERNAMEParameter = v_USERNAME != null ?
                new ObjectParameter("V_USERNAME", v_USERNAME) :
                new ObjectParameter("V_USERNAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_OBTENER_ID_USUARIO", v_USERNAMEParameter, v_ID_USUARIO);
        }
    
        public virtual int SP_OBTE_ID_USUARIO(string v_USERNAME, ObjectParameter v_ID_USUARIO)
        {
            var v_USERNAMEParameter = v_USERNAME != null ?
                new ObjectParameter("V_USERNAME", v_USERNAME) :
                new ObjectParameter("V_USERNAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_OBTE_ID_USUARIO", v_USERNAMEParameter, v_ID_USUARIO);
        }
    
        public virtual int SP_ADD_CARRITO_ESCRITORIO1(string v_USERNAME, Nullable<decimal> v_ID_PRODUCTO, Nullable<decimal> v_CANTIDAD, ObjectParameter v_SALIDA)
        {
            var v_USERNAMEParameter = v_USERNAME != null ?
                new ObjectParameter("V_USERNAME", v_USERNAME) :
                new ObjectParameter("V_USERNAME", typeof(string));
    
            var v_ID_PRODUCTOParameter = v_ID_PRODUCTO.HasValue ?
                new ObjectParameter("V_ID_PRODUCTO", v_ID_PRODUCTO) :
                new ObjectParameter("V_ID_PRODUCTO", typeof(decimal));
    
            var v_CANTIDADParameter = v_CANTIDAD.HasValue ?
                new ObjectParameter("V_CANTIDAD", v_CANTIDAD) :
                new ObjectParameter("V_CANTIDAD", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ADD_CARRITO_ESCRITORIO1", v_USERNAMEParameter, v_ID_PRODUCTOParameter, v_CANTIDADParameter, v_SALIDA);
        }
    
        public virtual int SP_OBTENER_CANTIDAD_SUBTOTAL_Y_TOTAL_ESCRITORIO(string v_USERNAME, ObjectParameter v_CANTIDAD, ObjectParameter v_SUB_TOTAL, ObjectParameter v_TOTAL)
        {
            var v_USERNAMEParameter = v_USERNAME != null ?
                new ObjectParameter("V_USERNAME", v_USERNAME) :
                new ObjectParameter("V_USERNAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_OBTENER_CANTIDAD_SUBTOTAL_Y_TOTAL_ESCRITORIO", v_USERNAMEParameter, v_CANTIDAD, v_SUB_TOTAL, v_TOTAL);
        }
    
        public virtual int SP_ADD_CARRITO_ESCRI(string v_USERNAME, Nullable<decimal> v_ID_PRODUCTO, Nullable<decimal> v_CANTIDAD, ObjectParameter v_SALIDA)
        {
            var v_USERNAMEParameter = v_USERNAME != null ?
                new ObjectParameter("V_USERNAME", v_USERNAME) :
                new ObjectParameter("V_USERNAME", typeof(string));
    
            var v_ID_PRODUCTOParameter = v_ID_PRODUCTO.HasValue ?
                new ObjectParameter("V_ID_PRODUCTO", v_ID_PRODUCTO) :
                new ObjectParameter("V_ID_PRODUCTO", typeof(decimal));
    
            var v_CANTIDADParameter = v_CANTIDAD.HasValue ?
                new ObjectParameter("V_CANTIDAD", v_CANTIDAD) :
                new ObjectParameter("V_CANTIDAD", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ADD_CARRITO_ESCRI", v_USERNAMEParameter, v_ID_PRODUCTOParameter, v_CANTIDADParameter, v_SALIDA);
        }
    
        public virtual int SP_DELETE_CARRITO_ESCRIT(string v_USERNAME, Nullable<decimal> v_ID_PRODUCTO, ObjectParameter v_SALIDA)
        {
            var v_USERNAMEParameter = v_USERNAME != null ?
                new ObjectParameter("V_USERNAME", v_USERNAME) :
                new ObjectParameter("V_USERNAME", typeof(string));
    
            var v_ID_PRODUCTOParameter = v_ID_PRODUCTO.HasValue ?
                new ObjectParameter("V_ID_PRODUCTO", v_ID_PRODUCTO) :
                new ObjectParameter("V_ID_PRODUCTO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_CARRITO_ESCRIT", v_USERNAMEParameter, v_ID_PRODUCTOParameter, v_SALIDA);
        }
    
        public virtual int SP_CLEAN_CARRITO_ESCRIT(string v_USERNAME, ObjectParameter v_SALIDA)
        {
            var v_USERNAMEParameter = v_USERNAME != null ?
                new ObjectParameter("V_USERNAME", v_USERNAME) :
                new ObjectParameter("V_USERNAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CLEAN_CARRITO_ESCRIT", v_USERNAMEParameter, v_SALIDA);
        }
    
        public virtual int SP_REGISTRAR_COMPRA_ESCRIT(Nullable<decimal> v_ID_USUARIO, ObjectParameter v_SALIDA)
        {
            var v_ID_USUARIOParameter = v_ID_USUARIO.HasValue ?
                new ObjectParameter("V_ID_USUARIO", v_ID_USUARIO) :
                new ObjectParameter("V_ID_USUARIO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_REGISTRAR_COMPRA_ESCRIT", v_ID_USUARIOParameter, v_SALIDA);
        }
    }
}
