//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FermeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_PROD
    {
        public TIPO_PROD()
        {
            this.PRODUCTO = new HashSet<PRODUCTO>();
        }
    
        public decimal ID_TIPO { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal ID_FAMILIA { get; set; }
    
        public virtual FAMILIA_PROD FAMILIA_PROD { get; set; }
        public virtual ICollection<PRODUCTO> PRODUCTO { get; set; }
    }
}
